package org.demo.gmdemo.dto;

public enum AuditAction {
    SUBSCRIPTION_CREATED,
    SUBSCRIPTION_ACTIVATED,
    SUBSCRIPTION_RENEWED,
    SUBSCRIPTION_CANCELLED,
    VEHICLE_ASSIGNED,
    VEHICLE_UNSUBSCRIBED,
    CHARGE_SUCCESS,
    CHARGE_FAILED,
    LIMIT_EXCEEDED
}

